### ISSUE TITLE
Recyclerview scrolling doesn't stop when end is reached

### ISSUE THREAD

**Issue by chrismabotuwana** [peter1492/LongScreenshot#1]
When the screenshot process starts, it scrolls the Recyclerview up. But when the end of the recyclerview is reached, it doesnt stop taking screenshots and I cant scroll the recyclerview back up. And it doesn't register changes in onScrollStateChanged as well. Anyway to stop taking the screenshots and get the generated bitmap when bottom end of the recyclerview is reached?

**Comment by peter1492** [comment]
you have to call **longScreenshot.stopScreenshot();** manually, when you have to stop the screenshot
